name: recipe_app
description: App de recetas con TheMealDB API
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  translator: ^1.0.0
  http: ^1.2.1
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  image_picker: ^1.2.1
  # Añadido para gestionar la API Key de Anthropic de forma segura
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.5
  flutter_riverpod: ^2.6.1
  hive_flutter: ^1.1.0
  wakelock_plus: ^1.7.0
  hive: ^2.2.3
  intl: 0.20.2
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.6
  sqflite: ^2.4.2+1
  path: ^1.9.1
  uuid: ^4.6.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.15.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Escudo_sabor.png"
  adaptive_icon_background: "#F8F4F0" 
  adaptive_icon_foreground: "assets/images/Escudo_sabor.png"
  adaptive_icon_foreground_inset: 20

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/