name: recipe_app
description: App de recetas con TheMealDB API
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  translator: ^1.0.0
  http: ^1.2.1
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # 1. Añade esta dependencia aquí
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Escudo_sabor.png"
  # Aquí ponemos el color crema de tu app para que "se coma" cualquier borde
  adaptive_icon_background: "#F8F4F0" 
  adaptive_icon_foreground: "assets/images/Escudo_sabor.png"
  # Aumenta el inset a 20. Esto encogerá la imagen dentro del icono, 
  # haciendo que los bordes ajedrezados queden fuera del área visible (el círculo)
  adaptive_icon_foreground_inset: 20

flutter:
  uses-material-design: true
  # 3. Asegúrate de registrar la carpeta de assets
  assets:
    - assets/images/